name: Update gh-pages
on:
  schedule:
    - cron: '0 12 * * 1,4'
jobs:
  update-gh-pages:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: ./build.sh

    - name: Deploy to gh-pages/
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
